site_name: MathChain Wiki
site_description: In Math We Trust!
site_author: MathChain

site_url: http://docs.mathchain.org/
repo_url: https://github.com/mathwallet/docs.mathchain.org

dev_addr: 0.0.0.0:8000

copyright: Copyright &copy; 2018 MathChain

nav:
  - Home: index.md
  - English:
    - 'Introduction':
      - 'MATH Token': en/token.md
      - 'Networks': en/networks.md
    - 'GaloisL1':
      - 'Run a Validator Node ': en/tut_run_node.md
      - 'Set up MathWallet': en/gmathwalletl1.md
      - 'Set up PolkadotJS': en/gpolkadotjs.md
      - 'Smart Web Wallet Guide': en/gwebwallet.md
      - 'Faucet': en/tut_testnet_faucet.md
      - 'Tools': en/tools.md
      - 'API': en/substrate_api.md
      - 'SubQuery': en/subquery.md
    - 'GaloisL2':
      - 'Set up MathWallet': en/gmathwalletl2.md
      - 'Set up Metamask': en/gmetamask.md
      - 'Deploy a Smart Contract': en/smartcontract.md
      - 'Deploy MAT20 token': en/mat20.md
      - 'Deploy NFT token': en/nft.md
      - 'API': en/evm_api.md
      - 'GraphQL': en/graphql.md
  - 中文:
    - '通证': cn/token.md
    - '常用工具': cn/tools.md
    - '创建地址': cn/tut_create_account.md
    - '获取测试币': cn/tut_testnet_faucet.md
    - '运行节点': cn/tut_run_node.md
    - 'API':
      - 'MathChainL1 API': cn/substrate_api.md
      - 'MathChainL2 API': cn/evm_api.md

plugins:
  - search

theme:
  name: 'material'
  palette:
    primary: 'White'
    accent: 'indigo'
  logo: 'images/logo.svg'

extra:
  manifest: 'manifest.webmanifest'
  social:
    # - icon: fontawesome/brands/github-alt
    #   link: 'https://github.com/mathwallet'
    # - icon: fontawesome/brands/twitter-alt
    #   link: 'https://twitter.com/mathwallet'