site_name: MathChain Wiki
site_description: In Math We Trust!
site_author: MathChain

site_url: http://docs.mathchain.org/
repo_url: https://github.com/mathwallet/docs.mathchain.org

dev_addr: 0.0.0.0:8000

copyright: Copyright &copy; 2018 MathChain

nav:
    - Home: index.md
      - English:
      - 'What is MathChain?': en/intro_en.md
      - 'MATH Token': en/token_en.md
      - 'Modules': en/modules_en.md
      - 'Applications': en/applications_en.md
      - 'For Developers': en/for_dev_en.md
      - 'For Individuals': en/for_ind_en.md
      - 'Milestone': en/milestone.md
      # - 'Run Node': en/tut_run_node.md
    - 中文:
      - '通证': cn/token.md
      - '常用工具': cn/tools.md
      - '创建地址': cn/tut_create_account.md
      - '获取测试币': cn/tut_testnet_faucet.md
      - '运行节点': cn/tut_run_node.md
      - 'API':
        - 'Substrate Runtime': cn/substrate_api.md
        - 'EVM': cn/evm_api.md
        
plugins:
    - search

theme:
  name: 'material'
  palette:
    primary: 'White'
    accent: 'indigo'
  logo: 'images/logo.svg'

extra:
  manifest: 'manifest.webmanifest'
  social:
    # - icon: fontawesome/brands/github-alt
    #   link: 'https://github.com/mathwallet'
    # - icon: fontawesome/brands/twitter-alt
    #   link: 'https://twitter.com/mathwallet'