site_name: MathChain Wiki
site_description: In Math We Trust!
site_author: MathChain

site_url: http://docs.mathchain.org/
repo_url: https://github.com/mathwallet/docs.mathchain.org

dev_addr: 0.0.0.0:8000

copyright: Copyright &copy; 2018 MathChain

nav:
  - Home: index.md
  - English:
    - 'Introduction':
      - 'MATH Token': en/token.md
      - 'Architecture': en/arch.md
      - 'Networks': en/networks.md
      - 'Launch Roadmap': en/launch.md
    - 'GaloisL1':
      - 'Run a Validator Node ': en/tut_run_node.md
      - 'Set up MathWallet': en/gmathwalletl1.md
      - 'Set up PolkadotJS': en/gpolkadotjs.md
      - 'Smart Web Wallet Guide': en/gwebwallet.md
      - 'Faucet': en/tut_testnet_faucet.md
      - 'Tools': en/tools.md
      - 'L1-L2 Swap': en/l1l2swap.md
      - 'API': en/substrate_api.md
      - 'SubQuery': en/subquery.md
      - 'SecretStore':
        - 'API': en/secretstore_api.md
        - 'SmartWallet': en/sequencechart.md
        - 'Security': en/security.md
    - 'GaloisL2':
      - 'Set up MathWallet': en/gmathwalletl2.md
      - 'Set up Metamask': en/gmetamask.md
      - 'Deploy a Smart Contract': en/smartcontract.md
      - 'Deploy MAT20 token': en/mat20.md
      - 'Deploy NFT token': en/nft.md
      - 'API': en/evm_api.md
      - 'GraphQL': en/graphql.md
  - 中文:
    - '介绍':
      - 'MATH Token': cn/token.md
      - '架构': cn/arch.md
      - '网络介绍': cn/networks.md
      - '主网路线图': cn/launch.md
    - 'GaloisL1':
      - '运行节点':
        - '同步节点': cn/tut_run_node.md
        - '验证人节点': cn/tut_run_validator_node.md
      - '设置 MathWallet': cn/gmathwalletl1.md
      - '设置 PolkadotJS': cn/gpolkadotjs.md
      - '智能网页钱包教程': cn/gwebwallet.md
      - '水龙头': cn/tut_testnet_faucet.md
      - '常用工具': cn/tools.md
      - 'L1-L2 Swap': cn/l1l2swap.md
      - 'MathChainL1 API': cn/substrate_api.md
      - 'SubQuery': cn/subquery.md
      - 'SecretStore':
        - 'API': cn/secretstore_api.md
        - '智能钱包': cn/sequencechart.md
        - '安全性': cn/security.md
    - 'GaloisL2':
      - '设置 MathWallet': cn/gmathwalletl2.md
      - '设置 Metamask': cn/gmetamask.md
      - '部署智能合约': cn/smartcontract.md
      - '部署 MAT20 token': cn/mat20.md
      - '部署 NFT token': cn/nft.md
      - 'API': cn/evm_api.md
      - 'GraphQL': cn/graphql.md

plugins:
  - search

theme:
  name: 'material'
  palette:
    primary: 'White'
    accent: 'indigo'
  logo: 'images/logo.svg'

extra:
  manifest: 'manifest.webmanifest'
  social:
    # - icon: fontawesome/brands/github-alt
    #   link: 'https://github.com/mathwallet'
    # - icon: fontawesome/brands/twitter-alt
    #   link: 'https://twitter.com/mathwallet'
